language: python

addons:
  chrome: stable

before-install:
  - wget -N https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_mac64.zip -P ~/
  - unzip ~/chromedriver_mac64.zip -d ~/
  - rm ~/chromedriver_mac64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover