language: python

addons:
  chrome: stable

before-install:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_mac64.zip" -O
  - unzip chromedriver_mac64.zip -d ~/bin

python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - mkdir ~/.streamlit && touch ~/.streamlit/config.toml
  - streamlit config show > ~/.streamlit/config.toml
  - sed -i -e 's/baseUrlPath = ""/baseUrlPath = "http:\/\/covid19dataexplorer.com\/dev"/g' ~/.streamlit/config.toml
  - bash run.sh

notifications:
    email: false