language: python

before-install:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser

python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover