env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.27.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

script:
  - cat .dw/config | grep -o 'ey.*' | dw configure
  - mkdir ~/.streamlit && touch ~/.streamlit/config.toml
  - streamlit config show > ~/.streamlit/config.toml
  - sed -i -e 's/baseUrlPath = ""/baseUrlPath = "covid19dataexplorer.com\/dev"/g' ~/.streamlit/config.toml
  - bash run.sh

notifications:
    email: false